### ISSUE TITLE
Error accessing property coerce of undefined

### ISSUE THREAD

**Issue by joebalancio** [mio/express#20]
```
{ name: 'TypeError',
type: 'non_object_property_load',
message: 'Cannot read property \'coerce\' of undefined' }
```
This error happens when passing data that doesn't have an attribute as part of the Resource.

```
Resource = mio.Resource.extend()
Resource.post({keyNotExists: 'blah'})
```

I'll submit a PR.

**Comment by alexmingoia** [comment]
:disappointed: thanks

**Comment by joebalancio** [comment]
Did some more debugging and it happens in the specific case when a key does not exist and the value is a number string.

````
Resource.post({blah: '123'})
```

**Comment by joebalancio** [comment]
Here's where the error happens
https://github.com/mio/express/blob/master/lib/mio-express.js#L1018
