### ISSUE TITLE
Should mergeParams be updated to handle arrays?

### ISSUE THREAD

**Issue by joebalancio** [mio/express#7]
https://github.com/mio/express/blob/master/lib/mio-express.js#L718-L732

When posting an array, this method gets called on req.body (an array). The result is an awkward object. I'm sure this can affect things later down the line.

```
var foo = [1,2,3]
foo.bar = 4
console.log(foo) // => [1, 2, 3, bar: 4]
```

Array support for POST is low priority for me right now so you don't have to look into this, but it's a nice to have.

**Comment by alexmingoia** [comment]
Ah, yes. Thanks.
